version: 2.1

jobs:
  build: # name of your job
    docker:  
      - image: cimg/base:2021.04  # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
    steps:
      - checkout
      - run:
          name: "list command"
          command: |
            ls
            pwd
  build2:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: "Other commands"
          command: |
            whoami
            cd ./circleci && ls
            ls /
            pwd

workflows:
  version: 2
  mi-pipe-line:
    jobs:
      - build
      - build2:
          requires:
            - build
          filters:
            branches:
              only: master
          
